name: Test
env:
  TZ: "Asia/Tokyo"
  ACTIONS_RUNNER_DEBUG: "true"
  ACTIONS_STEP_DEBUG: "true"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "!main"

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: prepare
        run: npm ci
      - name: check lint
        run: npm run lint
      - name: check type
        run: npm run type
      - name: run test
        run: npm run test
